; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin32_lite]
platform = espressif32@6.10.0
board = lolin32_lite
framework = arduino
; Wi-Fi + BLE固件超过默认1.25MiB；保留双OTA槽，每槽1.875MiB。
board_build.partitions = min_spiffs.csv
lib_deps =
	emotibit/EmotiBit BMI160@^0.3.3
	askuric/Simple FOC@2.3.3


